application: scraping-data
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /table-images
  static_dir: stylesheets/table-images
- url: /.*
  script: test_scraping.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest